backend:
  name: git-gateway
  branch: master
media_folder: static/img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "text" }
          - { label: "Sub-title", name: "subTitle", widget: "text" }
          - {
              label: "Background Title",
              name: "urlBackground",
              widget: "image",
            }
      - label: "Sobre"
        name: "sobre"
        file: "content/sobre.md"
        fields:
          - { label: "Title", name: "title", widget: "text" }
          - { label: "Sub-title", name: "subTitle", widget: "text" }
          - {
              label: "Background Title",
              name: "urlBackground",
              widget: "image",
            }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Contato"
        name: "contato"
        file: "content/contato.md"
        fields:
          - { label: "Title", name: "title", widget: "text" }
          - { label: "Sub-title", name: "subTitle", widget: "text" }
          - {
              label: "Background Title",
              name: "urlBackground",
              widget: "image",
            }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "text" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Background Title", name: "urlBackground", widget: "image" }
      - { label: "Category", name: "category", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list" }
      - {
          label: "Slug",
          name: "slug",
          widget: "hidden",
          default: "{{year}}-{{month}}-{{day}}-{{slug}}",
        }
      - { label: "Body", name: "body", widget: "markdown" }
